import mongoose from 'mongoose';
const { Schema } = mongoose;

const PaymentSchema = new Schema({
  name: { type: String, required: true }, // The name of the person donating (e.g., "ajay")
  to_user: { type: String, required: true }, // The username of the creator receiving the money
  oid: { type: String, required: true }, // The Order ID generated by Razorpay
  message: { type: String }, // The custom message: "donated $20 with a message..."
  amount: { type: Number, required: true }, // The donation amount
  done: { type: Boolean, default: false }, // Becomes true ONLY when Razorpay confirms the payment was successful
}, 
{ 
  timestamps: true // Automatically adds createdAt and updatedAt
});

// Next.js fix: Check if the model exists before creating it
const Payment = mongoose.models.Payment || mongoose.model('Payment', PaymentSchema);

export default Payment;